<?php
return array (
  'kuyun' => 
  array (
    'status' => '1',
    'from' => 'kuyun',
    'show' => 'kanyun',
    'des' => 'http://okzyw.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '9999',
    'tip' => '来源：OK资源',
    'id' => 'kuyun',
  ),
  'zkm3u8' => 
  array (
    'status' => '1',
    'from' => 'zkm3u8',
    'show' => 'zkm3u8',
    'des' => 'zkm3u8',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '最快高清',
    'id' => 'zkm3u8',
  ),
  'zkyun' => 
  array (
    'status' => '1',
    'from' => 'zkyun',
    'show' => 'zkyun',
    'des' => 'zkyun',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '最快云',
    'id' => 'zkyun',
  ),
  'mbyun' => 
  array (
    'status' => '1',
    'from' => 'mbyun',
    'show' => '秒播云',
    'des' => 'mbkkk.com',
    'ps' => '0',
    'parse' => 'https://api.mb999.vip/index.php?url=',
    'sort' => '997',
    'tip' => '无需安装任何插件',
    'id' => 'mbyun',
  ),
  'mbckm3u8' => 
  array (
    'status' => '1',
    'from' => 'mbckm3u8',
    'show' => '秒播M3U8',
    'des' => 'mbkkk.com',
    'ps' => '1',
    'parse' => 'https://api.mb999.vip/index.php?url=',
    'sort' => '996',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'mbckm3u8',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'http://api.oopw.top/?v=',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
  'ckm3u8' => 
  array (
    'status' => '1',
    'from' => 'ckm3u8',
    'show' => 'ckm3u8',
    'des' => 'http://okzyw.com',
    'ps' => '1',
    'parse' => '//www.dplayer.tv/?url=',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'ckm3u8',
  ),
  'zuidall' => 
  array (
    'status' => '1',
    'from' => 'zuidall',
    'show' => '最大云播',
    'des' => 'http://www.zuidazy.net/',
    'ps' => '0',
    'parse' => '',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'zuidall',
  ),
  'zuidam3u8' => 
  array (
    'status' => '1',
    'from' => 'zuidam3u8',
    'show' => '最大m3u8',
    'des' => 'http://www.zuidazy.net/',
    'ps' => '1',
    'parse' => 'https://zuidajiexi.net/m3u8.html?url=',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'zuidam3u8',
  ),
  '135m3u8' => 
  array (
    'status' => '1',
    'from' => '135m3u8',
    'show' => '135m3u8',
    'des' => '135m3u8',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '99',
    'tip' => 'HD高速',
    'id' => '135m3u8',
  ),
  '135zy' => 
  array (
    'status' => '1',
    'from' => '135zy',
    'show' => '135zy',
    'des' => '135zy',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '99',
    'tip' => 'HDzy',
    'id' => '135zy',
  ),
);