<?php
namespace app\common\model;
use think\Db;
use think\Cache;
use think\helper\Arr;

class DoubanRecommend extends Base {
    // 设置数据表（不含前缀）
    protected $name = 'douban_recommend';

    // 定义时间戳字段名
    protected $createTime = '';
    protected $updateTime = '';

    // 自动完成
    protected $auto       = [];
    protected $insert     = [];
    protected $update     = [];

    public function  findData($data = null)
    {
        return parent::find($data); // TODO: Change the autogenerated stub
    }


}