<?php
namespace app\common\model;
use think\Db;
use think\Cache;
use think\helper\Arr;

class DoubanRecommend extends Base {
    // 设置数据表（不含前缀）
    protected $name = 'douban_recommend';

    // 定义时间戳字段名
    protected $createTime = '';
    protected $updateTime = '';

    // 自动完成
    protected $auto       = [];
    protected $insert     = [];
    protected $update     = [];

    public function  findData($data = null)
    {
        return parent::find($data); // TODO: Change the autogenerated stub
    }

    public function  apiListData($where, $pageSize = 0, $sort = "id asc", $limit = 18){

        $list  = $this
            ->alias('r')
            ->field('r.vod_id,r.name,v.vod_pic,v.vod_score,v.type_id,v.type_id_1,v.vod_total,v.vod_serial,v.vod_douban_score,v.vod_remarks')
            ->join('vod v','r.vod_id = v.vod_id','left')
            ->where($where)
            ->order($sort)
            ->limit($pageSize,$limit)
            ->select();
        $list  = objectToArray($list);
        $data = [];
        foreach($list as &$item){
            $data[] = [
                'img'   => mac_url_img($item['vod_pic']),
                'id'    => $item['vod_id'],
                'name'  => $item['name'],
                'score' => $item['vod_douban_score'] > 0 ? $item['vod_douban_score'] : $item['vod_score'],
                'msg'   => vodRemark($item),
            ];
        }
        return $data;

    }


}